default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-executables-have-shebangs
    -   id: requirements-txt-fixer
